/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  skill: [
    'skill/introduction',
    {
      label: 'Linux',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/linux',
        },
      ],
    },
    {
      label: 'C 语言',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'skill/C/C_brief_introduction',
        'skill/C/C_environment_settings',
        'skill/C/C_program_structure',
        'skill/C/C_basic_syntax',
        'skill/C/C_keyword',
        'skill/C/C_datetype',
        'skill/C/C_variable_constant',
        'skill/C/C_operator',
        'skill/C/C_control_flow',
        'skill/C/C_function',
        
        
      ],
    },

    // {
    //   label: 'C 语言',
    //   type: 'category',
    //   link: {
    //     type: 'generated-index',
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'skill/C',
    //     },
    //   ],
    // },

    {
      label: '硬件基础',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/hardware',
        },
      ],
    },
    {
      label: '杂项',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/other',
        },
      ],
    },
  ],
  tools: [
    'tools/introduction',
    'tools/everything-quick-search-local-files',
    'tools/windows-custom-right-click-menu',
    'tools/windows-terminal-beautify',
    'tools/vscode-config',
  ],
}

module.exports = sidebars
